### ISSUE TITLE
Оформление гитхаба не по госту

### ISSUE THREAD

**Issue by PatheticOTD** [Neon-Narwhal/course-work#1]
Здравствуйте, оформление вашего репозитория не соответствует нормам ГОСТ 12.33.442 от 6 мая. Исправьте недочеты и добавьте список источников

**Comment by Neon-Narwhal** [comment]
Здравствуйте, [PatheticOTD](https://github.com/PatheticOTD) 
Нам очень жаль, что оформление репозитория не соответствует вашему выдуманному ГОСТу, в следствие этому, ничего меняться не будет

**Comment by PatheticOTD** [comment]
Гост мною не выдуман. Если вам лень открыть первую ссылку в гугле, то я сделал это за вас: https://bit.ly/4iPaQ8Q
